#!/usr/bin/env groovy
pipeline {
    agent any
    stages {
        stage('Clean Workspace') {
            steps {
                CleanWs()
            }
        }
    }

    stage ('Got Checkout') {
        steps {
            git branch: 'main', credentialsId: 'rlr.para@gmail.com', url: 'https://github.com/rlrpara/MeusRendimentos.git'
        }
    }

    stage('Restore Packages') {
        steps {
            bat "msbuild /t:restore $(workspace)\\MeusRendimentos.sln"
        }
    }

    stage('Clean') {
        steps {
            bat "msbuild $(workspace)\\MeusRendimentos.sln /nologo /nr:false /p:platform=\"Any CPU\" /p:configuration=\"release\" /t:clean"
        }
    }

    stage('Build') {
        steps {
            bat "msbuild $(workspace)\\MeusRendimentos.sln /nologo /nr:false /p:platform=\"Any CPU\" /p:configuration=\"release\" /t:clean;restore;rebuild"
        }
    }

    stage('Running unit tests') {
        steps {
            bat "dotnet test $(workspace)\\MeusRendimentos.sln"
        }
    }
}